### ISSUE TITLE
Issue after installing 

### ISSUE THREAD

**Issue by fdkfla** [ozancaglayan/python-emotiv#16] opened 2015-02-19 11:56 UTC
I run the command  ` python epoc.py ` , but the following error happened : 
 
Traceback (most recent call last):
  File "epoc.py", line 442, in <module>
    sys.exit(main())
  File "epoc.py", line 416, in main
    e = EPOC()
  File "epoc.py", line 173, in __init__
    self.enumerate()
  File "epoc.py", line 208, in enumerate
    print "Devices found: %d" % len(devices)
TypeError: object of type 'generator' has no len()

I have tried all solutions you suggest in previouse issues, but it does not work

**Comment by fdkfla** [comment] 2015-02-20 14:29
UPDATE : 
I have commented the line 208 , and the following error appear : 
`   Traceback (most recent call last):
  File "epoc.py", line 442, in <module>
    sys.exit(main())
  File "epoc.py", line 416, in main
    e = EPOC()
  File "epoc.py", line 173, in __init__
    self.enumerate()
  File "epoc.py", line 213, in enumerate
    for dev in devices:
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1185, in device_iter
    ) and (custom_match is None or custom_match(d)):
  File "epoc.py", line 178, in _is_epoc
    manu = usb.util.get_string(device, 1024, device.iManufacturer)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 273, in get_string
    return buf[2:buf[0]].tostring().decode('utf-16-le')
  File "/usr/lib/python2.7/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode byte 0x00 in position 6: truncated data
`

**Comment by ixjlyons** [comment] 2015-04-13 19:43
The updated problem is caused by a breaking change in [pyusb commit dac7893](https://github.com/walac/pyusb/commit/dac78933f6a6eaf5ae82f48e2f4e7d1733dc2f98): the `length` argument in `usb.util.get_string()` has been removed.

As mentioned in issue #12, I have started [a fork](https://github.com/ixjlyons/python-emotiv) of this project to keep it up to date with recent versions of pyusb. The fix for this issue can be seen [here](https://github.com/ixjlyons/python-emotiv/commit/a63c5d411c0dbe6ae9fcf08cb96c2421c3a7e4d1) if you'd like to just implement it yourself (very small diff).

**Comment by bcimindworks** [comment] 2015-05-05 07:37
Thanks @ixjlyons , I encountered the same problem and your forked version really helps!

**Closed** 2015-07-07 08:44 UTC
