### ISSUE TITLE
Error running epoc.py

### ISSUE THREAD

**Issue by saatvikshah1994** [ozancaglayan/python-emotiv#12] opened 2014-11-15 17:43 UTC
I built the package using 
<code>python setup.py install</code>
It installs with the following message
error: could not delete '/etc/udev/rules.d/99-emotiv-epoc.rules': Permission denied

Anyways when I run the file epoc.py Im getting the following error
Traceback (most recent call last):
  File "epoc.py", line 442, in <module>
    sys.exit(main())
  File "epoc.py", line 416, in main
    e = EPOC()
  File "epoc.py", line 173, in __init__
    self.enumerate()
  File "epoc.py", line 208, in enumerate
    print "Devices found: %d" % len(devices)
TypeError: object of type 'generator' has no len()

**Comment by ixjlyons** [comment] 2015-04-13 19:36
The first thing to note is that the package setup is failing to install the udev rule. You can either run `python setup.py install` as root (e.g. `sudo python setup.py install`) or just manually copy the udev rule to `/etc/udev/rules.d/`.

The error when running `epoc.py` is caused by [pyusb commit b3ee6cd](https://github.com/walac/pyusb/commit/b3ee6cdfef8ffbe2a02694ba81ec451bf7a39681): `usb.core.find()` with `find_all=True` returns an iterator rather than a list, so calling `len()` on it no longer works. I recommend simply commenting out or removing the line with `print "Devices found...` (i.e. line 208 in `epoc.py`).

Since this project is unmaintained now, I have just started working on [a fork](https://github.com/ixjlyons/python-emotiv) to keep it up to date with recent versions of pyusb (>=1.0.0b2). This issue and issue #16 are fixed on the master branch.

**Closed** 2015-07-07 08:45 UTC
